### ISSUE TITLE
World boarder in skyblock

### ISSUE THREAD

**Issue by NadlieunderScore** [KranetMC/elixir-network#12]
It is possible to go through the world border with trees and have them grow inside of you and push you through the boarder. Have not tested yet just a theory

**Comment by KranetMC** [comment]
I've just gone and tested this, and it seems this is possible, but only with the best of luck. Anyways the other side is claimed by the plugin itself so you would just die. Anyways, thanks for submitting this as it shows our dev team what to improve!

**Comment by KranetMC** [comment]
I've tried with a door and it seems like you can go through the border. Our dev team is looking into this issue. Thanks.

**Comment by KranetMC** [comment]
I've had a look and until islands start getting larger or there are more, we should be good. I will close this for now.
